name = "faith-brilliant-stars-school"
compatibility_date = "2023-12-01"

[build]
command = "cd frontend && npm install && npm run build"
cwd = "."
watch_dir = "frontend"

[[build.upload]]
format = "directory"
dir = "frontend/build"